<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"></a>
            <a class="brand" href="/"><img src="<?=$this->resource('images/logo.png','VivoSandboxModule')?>" height="20" width="88"></a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active">
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown</a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Action</a>
                            </li>
                            <li>
                                <a href="#">Another action</a>
                            </li>
                            <li>
                                <a href="#">Something else here</a>
                            </li>
                            <li class="nav-header">
                                Nav header
                            </li>
                            <li>
                                <a href="#">Separated link</a>
                            </li>
                            <li>
                                <a href="#">One more separated link</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form pull-right">
                    <input class="span2" type="text" placeholder="Email">
                    <input class="span2" type="password" placeholder="Password">
                    <button type="submit" class="btn">
                        Sign in
                    </button>
                </form>
                <!-- <p class="navbar-text pull-right">

                      Logged in as <a href="#" class="navbar-link">Username</a>

                    </p> -->
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="span3">
            <div class="well sidebar-nav">
                <?=$menu?>
                    <ul class="nav nav-list">
                        <li class="nav-header">
                            <a href="#">Sidebar</a>
                        </li>
                        <li class="active">
                            <a href="#">Link</a>
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li class="nav-header">
                            Sidebar
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Link</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#">Link</a>
                                </li>
                                <li>
                                    <a href="#">Link</a>
                                </li>
                                <li>
                                    <a href="#">Link</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li class="nav-header">
                            Sidebar
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                        <li>
                            <a href="#">Link</a>
                        </li>
                    </ul>
            </div>
            <!--/.well -->
            <?=$leftPanel?>
        </div>
        <!--/span-->
        <div class="span9">
            <ul class="breadcrumb">
                <li>
                    <a href="#">Home</a>
                    <span class="divider">
                        /
                    </span>
                </li>
                <li>
                    <a href="#">Library</a>
                    <span class="divider">
                        /
                    </span>
                </li>
                <li class="active">
                    Data
                </li>
            </ul>
            <?=$param;?>
                <?/* <div class="hero-unit">
                    <h1>
                        Hello, world!
                    </h1>
                    <p>
                        This is a template for a simple marketing or informational website. It
                        includes a large callout called the hero unit and three supporting pieces
                        of content. Use it as a starting point to create something more unique.
                    </p>
                    <p>
                        <a class="btn btn-primary btn-large">Learn more »</a>
                    </p>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus
                    ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo
                    sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed
                    odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
            <!--/span-->
            <div class="span4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus
                    ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo
                    sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed
                    odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
            <!--/span-->
            <div class="span4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus
                    ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo
                    sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed
                    odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
            <!--/span-->
        </div>
        <!--/row-->
        <div class="row-fluid">
            <div class="span4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus
                    ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo
                    sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed
                    odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
            <!--/span-->
            <div class="span4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus
                    ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo
                    sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed
                    odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
            <!--/span-->
            <div class="span4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus
                    ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo
                    sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed
                    odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
            <!--/span-->
        </div>
        <!--/row-->
        */?>
    </div>
    <!--/span-->
</div>
<!--/row-->
<hr>
<footer>
    <p>
        © Company 2012
    </p>
    <?=$footer?>
</footer>
<!--/.fluid-container-->
<?=$undefinedPanel?>
